files:
  include: 'css-build/**/*.scss'

rules:
  no-vendor-prefixes:
    - 0
  no-css-comments:
    - 0
  no-empty-rulesets:
    - 0
  property-sort-order:
    - 0
  class-name-format:
    - 0
  force-pseudo-nesting:
    - 0
  mixins-before-declarations:
    - 0